### ISSUE TITLE
Error on loading in QGIS 3 (master)

### ISSUE THREAD

**Issue by g-sherman** [elpaso/qgis-ipythonconsole#10]
OSX Sierra, iPython QGIS console version 1.7

Error at startup: 
Traceback (most recent call last):
	  File "/Users/gsherman/.qgis3/python/plugins/IPyConsole/IPyConsole.py", line 343, in shout
			    self.control._append_before_prompt_pos = self.control._get_cursor().position()
			AttributeError: can't set attribute
			
Console seems to function normally after load.

**Comment by elpaso** [comment]
Thanks for the report, I'll have a look when I'll be able to test master on OSX.

**Comment by elpaso** [comment]
@g-sherman would you please test if the last commit fixes the issue?
