### ISSUE TITLE
Sometimes on QGIS3 close: AttributeError: 'IPyConsole' object has no attribute 'dock' 

### ISSUE THREAD

**Issue by rduivenvoorde** [elpaso/qgis-ipythonconsole#16]
See title: I get the following dialog sometimes when I close, not precisely clear when it comes.
I tried to reproduce it, but sometimes it is gone for some time, but then at a certain time it returns and then stays on every close.

![error while unloading plugin ipyconsole_319](https://user-images.githubusercontent.com/731673/36780053-2a963230-1c72-11e8-9e56-0ca9acafcda0.png)

**Comment by rduivenvoorde** [comment]
Mmm, thought to do a PR, then saw that it already seems fixed:

https://github.com/elpaso/qgis-ipythonconsole/commit/446df34f221c7b7c711f4999607ead7fefb92c44

Little strange, as it seems that half of this fix is in my plugin (v 1.8 in QGIS3 from official plugin repo):
- there is no `'self.dock = None' `in the __init__
but there is a `if self.dock is not None:` in the unload

**Comment by elpaso** [comment]
Fixed in latest release
