### ISSUE TITLE
print() output into ipython console

### ISSUE THREAD

**Issue by marioba** [elpaso/qgis-ipythonconsole#17]
Is there a way to show the `print()` output from a python plugin into the ipython console instead of the standard qgis python console? (I know I should not use `print()` into a plugin... :) )

**Comment by elpaso** [comment]
Hi Mario, I'm sorry, I have no idea if this is possible, maybe there is a way to do that.
You can use `QgsMessagelog.logMessage` to print into QGIS logs though.

**Comment by marioba** [comment]
Thanks, Alessandro. I will try to find a way to do it.
