### ISSUE TITLE
error on activate or desactivate plugin

### ISSUE THREAD

**Issue by geostonemarten** [elpaso/qgis-ipythonconsole#21]
Desactivate the plugin cause error.

**Error**
AttributeError: 'IPyConsole' object has no attribute 'dock' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 392, in unloadPlugin
    plugins[packageName].unload()
  File "C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\IPyConsole\IPyConsole.py", line 138, in unload
    if self.dock is not None:
AttributeError: 'IPyConsole' object has no attribute 'dock'

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.2.2-Bonn Bonn, 26842169e9 

Chemin Python :
C:/OSGEO4~1/apps/qgis/./python
C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:\OSGEO4~1\apps\Python36\lib\site-packages\win32
C:\OSGEO4~1\apps\Python36\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python36\lib\site-packages\Pythonwin
C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by elpaso** [comment]
Fixed in latest release
