### ISSUE TITLE
Loading Errors

### ISSUE THREAD

**Issue by dmofot** [elpaso/qgis-ipythonconsole#6]
System: QGIS 2.8.3-Wien on Mac OSX 10.10.5 with ipythonconsole 1.2

The plugin fails to load, giving an initGUI() error.  The real error is `AttributeError: 'QAction' object has no attribute 'activated'`.  After some searching I found there is indeed no `activated` attribute, but there is a `triggered`.  Replacing lines 94-97 with:
```python
        self.docked_action.triggered.connect(self.docked)
        self.windowed_action.triggered.connect(self.windowed)
        self.default_action.triggered.connect(self.default)
        self.settings_action.triggered.connect(self.show_settings)
```
fixed the initGui() error.

This brought up another issue.  Current IPython using `pip install IPython` is 4.0.0, which is incompatible with ipythonconsole, so needed to `pip install IPython==3.1.0`.

The plugin is now working.

**Comment by elpaso** [comment]
Thank you! 
Can you please make a pull request with your modifications? I'll check them and update the plugin as long as they works also on Linux.
